### ISSUE TITLE
[v1.0.0b] - Sidebar always starts open on mobile reload

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1090]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When loading the application on mobile or as a PWA on a mobile device the sidebar always defaults to open. It should default to closed. 

### Deployment

Docker (Linux)

**Comment by zierbeek** [comment]
I thought it was a feature 😅

**Comment by zierbeek** [comment]
This would have to do with #906 ?

**Comment by Miroito** [comment]
I've started using Mealie on mobile since I deployed it a few days ago and I must admit I like that the sidebar is opened when you load the site.
What is not great and can probably be fixed is that sometimes clicking on a link in the sidebar gets you to that page but the sidebar doesn't disappear by itself.

**Comment by dorj222** [comment]
if this issue still has not been solved, may I claim this issue?
