### ISSUE TITLE
[v1.0.0b] - Recipe download fails with "401 Not authenticated"

### ISSUE THREAD

**Issue by Drumstickx** [mealie-recipes/mealie#1171]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Downloading a recipe fails with error "401 Not authenticated". This happens with both an admin and a regular user and with all recipes.

### Deployment

Docker (Linux)

**Comment by PFischbeck** [comment]
For anyone tackling this: the problem seems to be that the API endpoint for the download (`/api/recipes/{slug}/exports/zip`) forces normal authentication, although this should be handled with the token that is passed as an URL parameter. So one could probably solve it by making this endpoint unauthenticated, moving it out of the `RecipeExportController`.
