### ISSUE TITLE
Wrong ingredients names

### ISSUE THREAD

**Issue by Toucani** [mealie-recipes/mealie#1184]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

While translating ingredient names on Crowdin I noticed that there are 3 dubious items:
* rape
* horse
* spek

I imagine these are just typos and should be:
* rapeseed
* horseradish
* speck

This looks super easy to fix, which I'll be happy to do, just let me know whether my assumptions are correct:)

### Deployment

Other

### Mealie Version

dev

**Comment by hay-kot** [comment]
> rape

Much to my surprise, this is _actually_ correct. https://www.recipetips.com/glossary-term/t--36959/rape.asp

That said, I'm going to get rid of it, there have already been a few "Uhhh what is this?" questions being raised.

> horse

Also a strange one, but correct. Horse is eaten in other parts of the world. I will probably remove it though, because it is _odd_

> spek

I think this one is actually an issue though. It should be Speck as far as I can tell.

---

This is why you don't blindly copy a list of "Top Ingredients" from wikipedia...

**Comment by hay-kot** [comment]
I've made the required changes here:

- https://github.com/hay-kot/mealie/pull/1176

**Comment by Toucani** [comment]
Great, thank you very much!

Yeah, I also did find usages for `rape` and `horse` but I thought it would be better not to use them in the original English version due to ambiguity:)
