### ISSUE TITLE
[v1.0.0b] - Backups all have the same Created date

### ISSUE THREAD

**Issue by epheterson** [mealie-recipes/mealie#1446]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I've made several backups since creating my Mealie instance across different days.

Browsing to Settings > Backups, all of them show the same "Created" date in the list. 

Their filenames show accurate dates, but the 'Created' column for all of them shows today.

### Deployment

Docker (Synology)

### Deployment Details

```
**Details**
Version: v1.0.0beta-3
Build: 56eb0bca7142715984c8028c4c881f086e979564
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.3.1

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success
```

**Comment by Bentipa** [comment]
It could be that, as `stat.ST_CTIME` is used for the "Created" date, the metadata of the file changes (because its read or something?) and therefore is always set to the current time (where the backup folder is read).
A solution is to use `stat.ST_MTIME`instead, which is the last modification date (for the backups this is always the creation date).
This works fine for me when testing. I will propose the solution via a PR.
