### ISSUE TITLE
Problem with Server error

### ISSUE THREAD

**Issue by niklask52t** [mealie-recipes/mealie#1457]
Ive installed the v1 via Docker
my docker-compose is:
[docker-compose.yml.txt](https://github.com/hay-kot/mealie/files/8987931/docker-compose.yml.txt)
when i try to connect to mealie i get this message:
![image](https://user-images.githubusercontent.com/50155520/175842647-8510bd1a-ddcf-4494-a5eb-9e97799cbfdf.png)
and thats my log file:
[mealie.log](https://github.com/hay-kot/mealie/files/8987951/mealie.log)
Cant find my problem, can anybody help me?

**Comment by niklask52t** [comment]
Found the problem just after opening this, the problem are my environments in the frontend part, but why? i copied the settings from the docker-compose on the github page

**Comment by hay-kot** [comment]
Well first of all, I think you need to do a little more due diligence before opening an Issue, this is the second issue you've opened in the last hour that you've resolved yourself shortly after opening. And if the first implied that this project doesn't maintain up to date docs when you didn't even take the time to visit the link in the README. 

- https://github.com/hay-kot/mealie/issues/1456

Second, you haven't provided the logs for the frontend container, nor have you provided any information about how you're deploying mealie other than your docker-compose file. Additionally you've completely ignored the issue template for both of the issues you filed so far. Since it looks like you've resolved this issue, if you tell me what it actually is I might be able to tell you why it happened.

**Comment by niklask52t** [comment]
Sorry for that, so first of all i only found templates for bugs, nothing like an issue template. I also visited the link in the readme, but thats the link to the old documentation and nowhere is noticed that theres a new documentation. 

Where can i find the logs for the front end? So i deployed it normally via docker compose and i "fixed" the issue, but i want to define the Theme variables, but thats the point where the server gets that error, at this point i need some help

**Comment by hay-kot** [comment]
This sounds like a bug with how theme variables are being applied.

You can find the logs for the frontend container by using docker `docker logs <container-name>`.

**Comment by niklask52t** [comment]
Okay thank you, i guess all my problems are solved. Sry again for the mess i did :/

**Comment by hay-kot** [comment]
Glad you got your error figured out. Sorry about being an ass about the whole thing. I've been getting a lot of messages and feeling a little overwhelmed lately with the project, and there was no reason to be an ass to you. Hope you don't think all open source maintainers are jerks. Cheers 🎉
