### ISSUE TITLE
[v1.0.0b] [Task] - Refactor Event Bus to Support Web Hooks

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1463]
### What is the problem this task addresses?

Currently Mealie has limited support for external integrations and does not provide any ability to adequately "sync" data between systems. The current even-bus implementation for Mealie is very limited and can't provide the necessary data that's needed to properly integrate deeply with different systems. 

Related PRs

- #1447

### Proposed/Possible Solution(s)?

**From PR 1447**

- We reimplement the Event Bus to actually work like an even bus, I.E. Controllers post events and we implement handlers that listen for the events and publish data based off that.
- I think off the bat we could just have two, Apprise and Web Hook listeners. This would allow us to use the same event system, but allow for generic web hooks to be used to embed more granular information.
- I think if we make those changes we'd just need to define what sort of data we'd need to embed in the web hooks. I'd have to defer to you on this one because you're actually trying to use the API so you'd know best.

**Here's a Diagram and what I'm thinking**

```mermaid
graph TD;
    Request --> B[Controller]
    B -- Publish Event --> C[Event Bus]
    C -- Event --> D[WebhookSubscriber]
    C -- Event --> E[AppriseSubscriber]
    D --> DB[Check Database For Entries]
    E --> DB
    DB -- Has Entries --> Publish
    DB -- No Entries --> NA[No Action]

```

Effectively the Controllers would publish events to the Event Bus which would kick off a background task that would call the subscribers allowing the Controllers to finish the request while the events are processed in the background. 

Next the EventBus class would call the subscribers and the subscribers would go take it from there. In the case of the Apprise we'd query the database for Notifies and perform the Apprise notifications for those events. In the case of Web Hooks, we query the Web Hooks table for Enabled listeners for specific events. 

---

Now that I write this down, It may make more sense to leave the Web Hook Table that way it is and instead add a field to the Notifiers table that just toggles a `is_webhook` field so if it's a Web Hook we send a POST request with the full data context, otherwise we use the apprise integration.

**Comment by michael-genson** [comment]
Yeah, I like this. And I agree it would be simpler to allow notifies to be marked as a webhook - right now "webhooks" are only schedule-based, while "notifiers" are what I'm using for event-based integrations.

So if you marked a notifier as a webhook, you'd get some different configuration options (namely you're providing the `POST` URL instead of the apprise URL).

---

The other area I think we need to work on is the content of the webhook, as well as the behavior of some of the APIs. Here are some typical sync behaviors I think we should support:

Content
---
The webhook should contain all the necessary information for the consumer to know which records changed to minimize fetch requests, and any basic information on what/why it changed.

It should contain:
* The record id (bonus points if we can also include the route, but optional)
* The CRUD operation (was the record created, updated, or deleted?)
* Who did the change, and how?
  * If performed by a user, the user's id
  * If using an API token, somehow the specific token should be identified (its id, its name, a user-supplied tag, etc.)
  * (Optional) I could see it being useful to differentiate between whether someone triggered it via the frontend vs via the API/backend, but that might be more hassle than it's worth

Granular subscription options
---
* Only subscribe to certain CRUD ops (only creates, only updates and deletes, etc.)
* Subscribe to child objects independently of parent objects (i.e. shopping list items)
* (Optional) Subscribe to certain users' changes (e.g. don't subscribe to my integration's changes). This can also be the burden of the API consumer instead

API behavior
---
* Bulk routes should either:
  1. Send an event for _each_ record that was created/updated/deleted (easiest to implement for the producer and the consumer)
  2. Send one macro-event with a summary of all records that were affected (i.e. a list of ids, or if the operations are mixed a list of objects that include the id + the operation) (more complicated to implement, but more efficient for the server)
* Specifically, when a recipe is added-to or removed-from a shopping list, the specific items that were affected are not returned
* I think I saw similar behavior with bulk creation of recipes, but I have to confirm that

---

The last thing I think we need to support is child records updating the `update_at` property of the parent records (i.e. shopping list item updates should change the `update_at` for its shopping list). This makes incremental/batch syncing easier (I can check if my list has been updated before fetching all the list items). This isn't strictly related to refactoring the event bus, but it will interact with the new behavior.

**Comment by michael-genson** [comment]
From #1450:

1. Would it make sense to embed this into a JWT token on login/generation, so if you generate an API token you can specify a token as "Integration" type and it will set a property in the JWT. That way we'd be able to use it across all requests and wouldn't need to add Query to every route?
2. Would it make more sense to use a custom header for this? Something like X-Source-ID. We can set that up on the base controller so it's accessible everywhere.

**Comment by hay-kot** [comment]
Pretty sure this is done and has been for some time...
