### ISSUE TITLE
[v1.0.0b] - Manually imported images not showing on "All recipes" page

### ISSUE THREAD

**Issue by cwrivers** [mealie-recipes/mealie#1713]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Some manually imported images not showing on "All recipes" page, after clicking into the recipe, it will show as normal on the individual recipe page, this shows that there is an image tied to the recipe. 

Copied from submit bug:
**Details**
Version: v1.0.0beta-4
Build: 13850cda1f9cb02a8c788030ba6cfa96bba33571
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.11.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

### Deployment

Docker (Linux), Unraid

### Deployment Details

Unraid using docker. Deployed V1 with separate api/frontend.

**Comment by Miroito** [comment]
I have the same issue, I can take this bug over.

More information in the form of an example:
- The url is not the same for both images:
The thumbnail in the "All Recipes" page will try to load this image:
`/api/media/recipes/41fe89b7-b496-4053-b418-f99ced33446b/images/min-original.webp`
In the recipe's own page:
`/api/media/recipes/41fe89b7-b496-4053-b418-f99ced33446b/images/original.webp`

Looking at one affected recipe, I found that the min-original image does not exist:
```
root@847d550b65ea:/app/data/recipes/41fe89b7-b496-4053-b418-f99ced33446b/images# ls
original.webp  tiny-original.webp
```

The issue seems to happen on recipes that have been imported via zip for me.
It looks like that given how the function `PillowMinifier.to_webp` is written, if the uploaded (original) picture extension is already webp, the min version will not be saved.

I don't really understand the design of this module, in my opinion, the code lacks a proper logic which ultimately leads to cases like this.

PR #1716

**Comment by hay-kot** [comment]
> I don't really understand the design of this module, in my opinion, the code lacks a proper logic which ultimately leads to cases like this.

This is not an appropriate way to communicate concerns about code. 'lacking proper logic' provides no information on what you think is wrong with the module, nor does it do **anything** to help the issue that you believe exists. If you can't provide  or even try to provide clear and concise examples of _why_ a section of code is problematic or provide a better solution, you can keep these kinds of comments to yourself.

**Comment by Miroito** [comment]
> This is not an appropriate way to communicate concerns about code. 'lacking proper logic' provides no information on what you think is wrong with the module, nor does it do **anything** to help the issue that you believe exists. If you can't provide or even try to provide clear and concise examples of _why_ a section of code is problematic or provide a better solution, you can keep these kinds of comments to yourself.

I understand this comment I made is irritating, I did not want to go into the details because this issue is not the right place for it. Hence this vague statement I made.

If you want to discuss these concerns a place should be made for it.
