### ISSUE TITLE
NLP Model training for German / General translations

### ISSUE THREAD

**Issue by mx2k** [mealie-recipes/mealie#1812]
Hello,

I love mealie, but I do not love the accuracy of NLP for German, since the model is, as described in the manual, only trained in English. Is there a way of contributing to the NLP model training for German? Are there any resources or links where I might start with that topic? (total AI noob, but this feels like something a noob could start with, provided the internet has a tutorial somewhere)

One thing about the German translation I noticed: In the UI it states 99% completeness of German translation. On the translation contribution website it states 100% translation complete. I cannot approve these percentages. 
Most of the general UI is translated, but any systems settings dialog or dialogues related to the parser are still with all English stings. Feels subjectively way more than 1%, despite it states 99% or 100% competition, depending where you look. I run on the docker nightly builds, currently 1.0 beta 5

**Comment by PFischbeck** [comment]
Regarding your second point about how much of the UI is translated already: This is true, and not specific to German. Not all strings are localizable yet, since this requires code changes (see #1532, #1565). Once this is done for the remaining UI elements, the percentages will be more accurate, and translation on https://crowdin.com/project/mealie can continue!
