### ISSUE TITLE
[v1.0.0b5] - scapter is still 14.20.0

### ISSUE THREAD

**Issue by remb0** [mealie-recipes/mealie#2034]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Not sure if it's a bug or someting i can't see/find.   but I'm runing the latest version in a docker container, but the scaper is still on version [14.20.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.20.0)   instead of 14.26 link the demo page or 14.27 like the github project of the scraper itself.

Is this by design?  or can I manual upgrade it?

### Deployment

Docker (Linux)

**Comment by RealFoxie** [comment]
The beta release (v1.0.0beta-5) which is "latest" I think (instead of "nightly"), has 14.20.0
The demo page uses the nightly I think, even though it says it's v1.0.0beta-5 on the login page. The reason is that the "I made this" functionality is on the demo, but I'm pretty sure "I made this" is currently only available in nightly, not the beta's.

**Comment by hay-kot** [comment]
@RealFoxie is correct. The demo is automatically deployed whenever the nightly is updated. FYI, in the future if you have an issue, especially related to versions, be sure to provide your deployment details otherwise we're all just guessing. 

If you want the latest recipe-scraper you can pull the nightly images, otherwise you can wait until the we hit RC-1, which may take some time to wrap up the last feature
