### ISSUE TITLE
Interface unusable with 5,000+ recipes

### ISSUE THREAD

**Issue by domini17** [mealie-recipes/mealie#2076]
Really love this software. It's entirely possible my niche use case is simply out of scope of any intended usage. Loaded 5000+ recipes into Mealie (w/ postgresql backend + RAM / CPU up the wazoo) via the API and the software just takes 5+ minutes to navigate between pages.

**Comment by michael-genson** [comment]
Wow, that's a lot of recipes!
There are a few major optimizations coming down the pipeline soon, so look out for a new version on nightly and see if performance improves for you. It should be pretty drastic.

See PR #2062 and PR #2070

**Comment by fleshgolem** [comment]
Huh, thats interesting...
So, #2070 shouldnt really do anything performance-wise, #2062 should alleviate this at least a little bit, but I'm still surprised that things are this bad in the first place since everything is paginated and never loads more than ~64 recipes at once, so this really shouldnt ever take that long unless something else is really fucked up.
My gut says that there are probably places where the database is not indexed properly somewhere (i never really checked for that, when doing the last performance thing, for some reason) otherwise loading times shouldnt grow like that. I can take a look at it at some point in the next few days, I think, I just need to find some quick way to generate this amount of data in the first place :). If you are in the discord and know how-to and are comfortable with sharing a dump of your database (you can remove the users table of course), feel free to contact me. Otherwise it will probably take a bit longer

The only part of the app that I assume will be unsalvagable as of right now is the search, as that always tries to load the full dataset and does things client-side

**Comment by fleshgolem** [comment]
I talked to @domini17 on discord and it turns out they were using 0.5.6, so I assume noone has any interest in improving things on that end
I could still find some issues with the current setup, but these would cause a page load with 5000 recipes to be more around 1-2sec rather than the mentioned 5 minutes. Still not ideal, but probably out of scope of this issue, so i will do a followup one

**Comment by hay-kot** [comment]
- #2117

Fixes the majority of these issues you'll see with this kind of volume. There are two more areas that need to still be fixed. See here for the list and tracking.

- https://github.com/hay-kot/mealie/issues/2118
