### ISSUE TITLE
Recipe parser converting units

### ISSUE THREAD

**Issue by nathcoad** [mealie-recipes/mealie#2086]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] I have checked for existing issues that have been resolved in v1-beta

### What is the issue you are experiencing?

I'm unsure whether this is a bug or something that I just can't find how to change in the documentation.

It seems that mealie will now automatically convert units when parsing a recipe from a URL. Eg https://www.taste.com.au/recipes/rosemary-beef-potato-meatloaf/ca9173af-a01f-44c9-a229-947493a70574 specifies some ingredients measured by tablespoon but when imported into mealie it has converted into grams, eg "2 tbsp wholegrain mustard" changes to "46.80 gram wholegrain mustard".

I recognise that some people may expect and appreciate this conversion feature, but is it possible to disable it somehow?

Thanks so much for such an awesome application.

### Deployment

Docker (Linux)

### Mealie Version

v1.0.0beta-5

**Comment by RealFoxie** [comment]
It is not mealie nor the scraper that does the conversion. It is the website itself that saves the recipe with the conversion in its structures data. You can check this on https://search.google.com/test/rich-results
The structured data that the website has embedded (and which the scraper uses) has these conversions instead of the original amounts that are shown to the user.

So unfortunately only the website developer can fix this :(

**Comment by nathcoad** [comment]
Thanks for the quick response and explanation. I hadn't considered that possibility but it does make a lot of sense.
