### ISSUE TITLE
[v1.0.0b] - Permission denied when saving "I Made This" on locked recipe

### ISSUE THREAD

**Issue by smoofus** [mealie-recipes/mealie#2089]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Permission denied when saving "I Made This" on locked recipe.  Entry is added to timeline but "Last Made" time is not updated

```
02/03/2023 4:05:01 PM
INFO:     172.20.0.2:34988 - "POST /api/recipes/quick-pickled-red-onions/timeline/events HTTP/1.1" 201 Created
02/03/2023 4:05:01 PM
ERROR: 03-Feb-23 16:05:01 	Permission Denied on recipe controller action
```

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Ah yeah, only the owner can update the recipe's last made timestamp if it's locked. I'd say that's _probably_ not what we want.

@hay-kot, thoughts in this? I'm guessing we want to change this behavior. If we do, do you think we should just implement a special route that works around it (i.e. ignore the "locked" check), or would you rather have some sort of "whitelisted fields" check? I'm on the fence because on one hand, a "workaround route" isn't scalable, but on the other hand, if we're only ever going to do this once or twice it's probably not worth making things more complicated. I'm happy to work on either
