### ISSUE TITLE
[v1.0.0b] - Bulk Category/Tag Dropdown doesn't update properly

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#2200]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Dropdown on the Dialog does not update when going from Category to Tag or Tag to Category. For example.

If you you open the dropdown, select Category and apply a Category. If you then go Tag the items shown in the selector will be Categories. Whichever is chosen first will show. 

You can work around this by refreshing the page between actions

### Deployment

Docker (Linux), Docker (Windows), Docker (Synology), Unraid, Other

**Comment by michael-genson** [comment]
Do you know which dropdown this is referring to? I vaguely remember this issue but I don't remember where it is

**Comment by smstroble** [comment]
This happens on the Recipe Data page `/group/data/recipes/`

**Comment by FancyNerd92** [comment]
I have problem with automatic tags from recipe on bulk import. in single mode you have the option to use "import original keywords as tags" but in bulk mode you don't have this option. So in my case more than 2K recipies must upload url by url to have this option? I want it because i use it for automatic ingridient tag on my recipes but i can't use it on bulk import... Please give me a clue! thanks!
