### ISSUE TITLE
[v1.0.0b] - recipes-API gives duplicates and forget some recipes

### ISSUE THREAD

**Issue by alexdetsch** [mealie-recipes/mealie#2208]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When asking the API like `/api/recipes?page=1&perPage=32` (with `page` increasing until `total_pages` limit) I thought, I get all recipes stored in mealie. But instead, I get some duplicates and some are forgotten. I get exactly the number of recipes I have in mealie, but as stated, some I get twice and others are missing. I didn't found any pattern in what order they reappear.

I also seen this problem in the frontend, as here also some recipes are missing and some appears twice.

I have 178 recipes. Following the indices of doubling recipes as provided by the api:
[0, 128]
[1, 97]
[3, 129]
[4, 130]
[6, 131]
[7, 100]
[8, 132]
[9, 133]
[10, 104]
[11, 106]
[12, 134]
[13, 107]
[14, 108]
[15, 135]
[16, 136]
[20, 137]
[21, 160]
[22, 112]
[24, 138]
[25, 114]
[26, 139]
[30, 140]
[31, 141]
[32, 142]
[33, 143]
[34, 144]
[35, 145]
[38, 146]
[40, 147]
[41, 148]
[42, 149]
[43, 115]
[45, 150]
[46, 151]
[47, 161]
[48, 116]
[50, 118]
[51, 119]
[52, 120]
[53, 152]
[55, 153]
[57, 154]
[58, 125]
[59, 155]
[60, 156]
[61, 157]
[62, 158]
[63, 159]
[65, 96]
[67, 98]
[68, 99]
[69, 101]
[70, 102]
[72, 103]
[74, 105]
[75, 109]
[78, 110]
[80, 111]
[81, 113]
[88, 117]
[89, 121]
[90, 122]
[91, 123]
[92, 124]
[93, 126]
[94, 127]

### Deployment

Docker (Linux)

### Deployment Details

I'm using the latest nightly, build [5b487464ea72a3d5faef175adfc41c31a69b497e](https://github.com/hay-kot/mealie/commit/5b487464ea72a3d5faef175adfc41c31a69b497e) with Postgres

**Comment by fleshgolem** [comment]
I tried this a few different ways now and I really cant reproduce it
Started from a fresh database and wrote a script that will generate me exactly 178 recipes with numbered names, so I can keep track of them. Then paged them via API to 32 entries and also looked at the frontend and its all listed exactly the way its supposed to (i.e. from number 178 downward with no dupes or gaps). I tried this on both sqlite and postgres. I then also randomly added some categories to my recipes to see if relations that get joined in the query make any difference, but they don't
TBH, I also dont quite understand what your id table is trying to convey, so that doesnt really help
Do you maybe have any further info on things that are happening or your setup? Are you sure that the data just doesnt exist in your DB like this and was just created wrongly (for whatever reason), can you look at your DB to check? Does the behaviour change in any way if you use different orderBy parameters (e.g. "name") in your query?

I also looked at the query that sqlalchemy emits here again and its basically this
```sql
SELECT anon_1.*, categories_1.*, tools_1.*, tags_1.*
FROM (SELECT recipes.*
FROM recipes
WHERE recipes.group_id = '{your_group_id}' ORDER BY recipes.created_at DESC
 LIMIT 32 OFFSET 0) AS anon_1 
LEFT OUTER JOIN (recipes_to_categories AS recipes_to_categories_1 JOIN categories AS categories_1 ON categories_1.id = recipes_to_categories_1.category_id) ON anon_1.id = recipes_to_categories_1.recipe_id 
LEFT OUTER JOIN (recipes_to_tools AS recipes_to_tools_1 JOIN tools AS tools_1 ON tools_1.id = recipes_to_tools_1.tool_id) ON anon_1.id = recipes_to_tools_1.recipe_id 
LEFT OUTER JOIN (recipes_to_tags AS recipes_to_tags_1 JOIN tags AS tags_1 ON tags_1.id = recipes_to_tags_1.tag_id) ON anon_1.id = recipes_to_tags_1.recipe_id ORDER BY anon_1.created_at DESC
```

I simplified it just a bit for readability, but that really is it. I fail to see how this could ever produce such a behaviour in any way. Can you run this directly in postgres as well (replacing ` {your_group_id}` and raising the offset as needed)  and maybe see if this also produces similar results?
