### ISSUE TITLE
[BUG] - Clicking Mealie header to return home does not reset search filters 

### ISSUE THREAD

**Issue by shiruken** [mealie-recipes/mealie#2259]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When browsing by category, tag, or tool via the sidebar, clicking on the header icon/name to return home does not clear the current filters. The URL properly updates to the website root but the filter persists.

### Deployment

Docker (Linux)

### Deployment Details

Version: omni-nightly
Build: 8d79773bf65eb6bfd9021963324d53a25aab3cde

**Comment by boc-the-git** [comment]
This still exists on latest nightly

**Comment by mcnamamj** [comment]
I was able to reproduce this.  I'm investigating now.

**Comment by mcnamamj** [comment]
This is my first project in Vue, so I'm gonna spec this out to make sure I'm going down a sane path.

Notes:
* `components/Domain/Recipe/RecipeExplorerPage.vue` has a `reset()` method that looks super handy
* `components/Layout/LayoutParts/AppHeader.vue` has the v-toolbar-title that has the @click event we want to adjust to somehow signal to RecipeExplorerPage that it's time to reset.

However, getting these two things to talk to each other is where I'm stuck.

Things I'm not using:
- emit because it isn't a direct parent/child relationship that we need to keep track of.
- props for the same reason.  These are distant relatives

So now I'm thinking I should use Nuxt.js's Vuex store at `frontend/store/index.js`....   This seems [like overkill](https://v2.nuxt.com/docs/directory-structure/store/).

Hmm.  How about this proposal: just have the browser actually ~reload the page when the logo is clicked?~
update: ^ reloading doesn't work: state persists.

Pausing for guidance.
