### ISSUE TITLE
[v1.0.0b] - Recipe timeline events are not automatically created if Meal Plan is scheduled from the recipe page

### ISSUE THREAD

**Issue by shiruken** [mealie-recipes/mealie#2344]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Meal Plan entries automatically add a recipe timeline event on the scheduled date (#2050). However, this appears to only work when scheduled from the Meal Planner page. Recipe timeline events are _not_ being created if added to the Meal Plan via the recipe page.

### Deployment

Docker (Linux)

### Deployment Details

Version: omni-nightly
Build: 03b7d9e20056d1e5dfed0648bd31faf13df285bb

**Comment by michael-genson** [comment]
Do you happen to have any server logs handy on the date of the scheduled mealplan? (e.g. if your meal was scheduled for April 9th, your logs for April 9th).

The event doesn't get posted to the timeline until the day of the mealplan, so if there's an error, that's where the logs would be

**Comment by Grygon** [comment]
I'm unable to reproduce the issue

- Added recipe for today from Meal Plan page
- Added recipe for today to Meal Plan from the Recipe
- Added recipe for today to Meal Plan from the recipe overview

Then triggered the `create_mealplan_timeline_events` task manually, and all 3 had entries created for today.
Reading through the code, the only things I could see us not completing this on would be is if there's some missing attribution for group/recipe/user on what's in the meal plan, but I don't see how that could be possible...

@shiruken are you still able to recreate this in nightly? If so, more info on reproducing the issue might be helpful, since I've been unable to.

**Comment by shiruken** [comment]
I haven't encountered this issue recently. I wonder if it was a byproduct of Meal Plan events that were scheduled _prior_ to transitioning to the nightly build.

I will close issue for now
