### ISSUE TITLE
[v1.0.0b] - Mailing via SMTP doesn't work

### ISSUE THREAD

**Issue by bobvmierlo** [mealie-recipes/mealie#2418]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

I'm trying to get mailing working with SMTP, I've set all the according env variables in my Docker container but the mailer keeps giving the error below.
I'm using other docker containers (e.g. Bookstack) with the same/similar settings without any issues.

`ERROR: 10-Jun-23 22:08:17 	{'RECIEVER@email.com': (553, b'5.7.1 <Mealie>: Sender address rejected: not owned by user SENDER@email.com')}`

Where my SMTP_USER and SMTP_FROM_EMAIL are both set to the emailadres where SENDER@email.com is in the error.

### Deployment

Docker (Linux)

### Deployment Details

**Details**
```
Versie: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Applicatie modus: Productie
Demo status: Niet Demo
API Poort: 9000
API-documentatie: Ingeschakeld
Databasetype: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: Yes
Docker Volumes: success
```

**Comment by Keule0010** [comment]
I have encountered the same problem. Installed Mealie yesterday by following the docs (version v1.0.0beta-5).
From the error message I realized that the email was being sent from Mealie and not SENDER@email.com, so I changed `SMTP_FROM_NAME=Mealie` to `SMTP_FROM_NAME=SENDER@email.com`, which worked. However, then the sender was obviously not displaying correctly. I looked a bit into the code, which looked fine to me and indeed worked without any problems. Maybe we are doing something wrong here or just have to wait for the next update. To be safe someone could add the from_addr parameter in the email send method.

```python
errors = server.send_message(msg)
#To
errors = server.send_message(msg, from_addr=self.mail_from_address)
```
Here https://github.com/hay-kot/mealie/blob/674774d073ff6e9aba90a8291a11e8e55ced44f6/mealie/services/email/email_senders.py#L46
and
https://github.com/hay-kot/mealie/blob/674774d073ff6e9aba90a8291a11e8e55ced44f6/mealie/services/email/email_senders.py#L53

But I'm not sure if that will help because it worked just fine for me locally, or if we are doing something wrong.

**Comment by regularguy01** [comment]
I to had to put in a real email address for the SMTP_FROM_NAME

**Comment by boc-the-git** [comment]
Are you guys able to confirm if this is still an issue in the latest nightly/RC2 versions?
Does this ultimately boil down to a documentation issue in terms of needing to clarify that an email address needs to be populated for env var `SMTP_FROM_NAME`?

**Comment by boc-the-git** [comment]
Also, what SMTP server/software are you using for this? Your full config, obfuscated where needed, would be useful.

**Comment by Keule0010** [comment]
I recently switched to the nightly build and everything works as expected. It looks like this is only an issue with the old version. Sorry, I totally forgot to update my post.

**Comment by boc-the-git** [comment]
Thanks for confirming!
