### ISSUE TITLE
[v1.0.0b] - Documentation error default credentials

### ISSUE THREAD

**Issue by lukyjay** [mealie-recipes/mealie#2445]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The documentation says to use the default credentials, but given the site is behind Cloudflare they're being removed from the page.

https://nightly.mealie.io/documentation/getting-started/installation/installation-checklist/#step-4-validate-installation

Step 3:
```
Default Credentials

Username: [[email protected]](https://nightly.mealie.io/cdn-cgi/l/email-protection)

Password: MyPassword
```

### Deployment

Other

**Comment by lukyjay** [comment]
The answer by the way, is: changeme@email.com

**Comment by michael-genson** [comment]
I'm not seeing it redacted, it looks fine to me:
![image](https://github.com/hay-kot/mealie/assets/71845777/2ca47c0d-cb52-4705-9b6a-afa96cd113fb)

**Comment by lukyjay** [comment]
That page isn't doing that for me anymore... Cloudflare must have some rules in place that switch this on and off

I am still seeing it on this page however:
https://nightly.mealie.io/documentation/getting-started/installation/backend-config/#api-environment-variables

**Comment by lukyjay** [comment]
![PXL_20230707_055843900.jpg](https://github.com/hay-kot/mealie/assets/5250189/ffd0bfb5-969e-4096-9521-2cd179c63d06)

**Comment by michael-genson** [comment]
Weird, still not doing it for me. Maybe you have something set up on your browser?
![image](https://github.com/hay-kot/mealie/assets/71845777/667666f2-dd0c-40e5-876e-ec23aa3fbf84)

**Comment by lukyjay** [comment]
> Weird, still not doing it for me. Maybe you have something set up on your browser?
> ![image](https://github.com/hay-kot/mealie/assets/71845777/667666f2-dd0c-40e5-876e-ec23aa3fbf84)
> 

It shows this URL: https://nightly.mealie.io/cdn-cgi/l/email-protection

Suggesting JavaScript isn't enabled but it is. It might be an adblocker. Perhaps we could replace the email with the username for the default login to help others who face this issue?

**Comment by Flightkick** [comment]
Stumbled upon this issue while looking for other issues. Like you correctly assumed, this happens because `nightly.mealie.io` is being proxied by Cloudflare and Email Address Obfuscation is enabled, this is a feature within Scrape Shield. The email address is substituted when Cloudflare thinks the visitor may not be a legitimate user, such as a bot. It may be difficult to trigger but I've been able to verify this through some public proxies and disabling JavaScript through an adblocker (so that Cloudflare can't run verification scripts).

The owner of the domain might be better off disabling the feature. You can find more info [here.](https://developers.cloudflare.com/support/more-dashboard-apps/cloudflare-scrape-shield/what-is-email-address-obfuscation/)
