### ISSUE TITLE
[BUG] - Tandoor migration does not parse ingredients/units if activated 

### ISSUE THREAD

**Issue by lmgarret** [mealie-recipes/mealie#2528]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

I'm not sure if this is a bug or a missing feature, I went with the former. The group I'm in has 'disable ingredient and units parsing/organization' toggled off. I imported some recipes from Tandoor, with ingredients and units set. The resulting recipes have a `1` as a quantity and no ingredient/unit set

### Steps to Reproduce

1. Set the group option 'disable ingredient and units parsing/organization' to OFF
2. Import recipes from tandoor using the migration tool. The recipes should have 'rich' units and ingredients. Sample export provided
3. Check in the imported recipe the ingredients quantities, they're all set to 1.
[tandoor_sample.zip](https://github.com/mealie-recipes/mealie/files/12466295/tandoor_sample.zip)

### Please provide relevent logs

No logs 

### Mealie Version

Latest nightly, using omni image. docker image sha256: 8ec73b5781646d77f6e0851b570de741c3d5dba38a12f364568076ebc12cba39

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
Currently we don't support migrating Tandoor's ingredients and units out of the box. You'll need to parse them yourself for now. 

There are a few reasons for this (including the fact that [the Tandoor migration is fairly new](https://github.com/mealie-recipes/mealie/pull/2438)), but mainly it has to do with how to handle matching foods/units to the existing food/unit store, as well as how to handle missing foods/units. Right now we don't have a reliable way to do the matching, so we either need to:
1. ignore the existing food store and blindly create new foods/units defined in Tandoor, probably creating duplicates
2. wipe the group's existing foods/units to ensure there are no duplicates, then create new ones using the Tandoor definitions

This is only a problem if you already have foods/units defined, which is unlikely since you're probably only migrating when you first spin up Mealie, however it _also_ means that you can't really use the seed function anymore (since, for the same reasons, it does not match to existing foods or prevent duplicates), which many users find super useful (I know I did when I started using Mealie).

I'd be open to working on a feature request to add support for conserving Tandoor's foods and units when migrating, but I'm hesitant until we refine food/unit matching. I could see a world where we add the option with a warning explaining the caveats above though, even before the matching issue is resolved.
