### ISSUE TITLE
[BUG] - Frontend vars don't work with new single-container setup (ghcr.io)

### ISSUE THREAD

**Issue by jondyer** [mealie-recipes/mealie#2577]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

When running the new single container setup as described at https://github.com/mealie-recipes/mealie/blob/mealie-next/docs/docs/documentation/getting-started/installation/sqlite.md, the app doesn't recognize frontend theming variables when they are tossed in with the backend ones, like so:
```
    environment:
    # Set Frontend ENV Variables Here
      - THEME_LIGHT_PRIMARY=#507B8F
      - THEME_LIGHT_ACCENT=#3B7064
      - THEME_DARK_PRIMARY=#507B8F
      - THEME_DARK_ACCENT=#3B7064
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - ...
```

### Steps to Reproduce

1) Start with the `docker-compose.yaml` listed here: https://github.com/mealie-recipes/mealie/blob/mealie-next/docs/docs/documentation/getting-started/installation/sqlite.md
2) Add any frontend theme vars
3) Fire it up and behold the lack of colors :(

### Please provide relevent logs

Logs at startup show `------APP SETTINGS------` followed by the backend vars, but none of the frontend ones appear.

### Mealie Version

ghcr.io/mealie-recipes/mealie:nightly

Side note: there's no build number displayed in-app for this single-container stuff
![image](https://github.com/mealie-recipes/mealie/assets/19843375/ba9df168-2f6f-4251-84aa-6c3968983d60)

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
I believe the env vars aren't being printed out at start up because they're not defined here: https://github.com/mealie-recipes/mealie/blob/79796ce4c20606901cc9340f0d00a2bfe84241d0/mealie/core/settings/settings.py#L25C7-L165

However, I'm not convinced that simply adding definitions for them there is sufficient for the frontend logic to pick them up; haven't looked into the finer detail there. I expect [this is the relevant program](https://github.com/mealie-recipes/mealie/blob/79796ce4c20606901cc9340f0d00a2bfe84241d0/frontend/nuxt.config.js), but not sure where `process.env` gets populated.
