### ISSUE TITLE
PWA incompatible message

### ISSUE THREAD

**Issue by PeterJT** [mealie-recipes/mealie#2642]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### What is the issue you are experiencing?

Launching PWA on Android 14 (Pixel 6a) results in initial error message

### Steps to Reproduce

Launch mealie in chrome browser
Select option to install Application
Initial launch of newly installed app results in error message "This app isn't compatible with latest version of Android. Check for an update or contact the app's developer."
App appears to work correctly and subsequent launches do not produce this message.

### Please provide relevent logs

n/a

### Mealie Version

Version
v1.0.0-RC1.1
![Screenshot_20231015-182041](https://github.com/mealie-recipes/mealie/assets/4331948/3925f609-c5e3-420f-8821-db23dedc9f5f)

### Deployment

Docker (Linux)

**Comment by boc-the-git** [comment]
Without having looked at the detail, I wonder if this is something to do with the nuxt libraries that are used to produce the PWA. I believe they're fairly old in the scheme of things.

**Comment by p0lycarpio** [comment]
I'm using version v1.0.0-RC1.0 and also had this error for a while. I don't know why but just trying again it works. I can't reproduce this error... Has Chrome Android been updated on my side or has the site data been deleted?

However, it is true that this can come from the configuration of nuxt-pwa and the fact that the version used is old. It also seems more updated, because of the release of Nuxt 3.
