### ISSUE TITLE
[SCRAPER] - Crock-pot.com

### ISSUE THREAD

**Issue by itsadamslife** [mealie-recipes/mealie#3010]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://www.crock-pot.com/on/demandware.store/Sites-crockpot-Site/default/Content-Show?cid=sweet-and-spicy-orange-chicken

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

          INFO: 19-Jan-24 18:15:12 	HTTP Request: GET https://www.allrecipes.com/recipe/141678/slow-cooker-pulled-pork/ "HTTP/1.1 200 OK"
          INFO: 19-Jan-24 18:15:12 	Image URL: ['https://www.allrecipes.com/thmb/jhwH3oEpLmIcJ4Adf4bRsvEJ0UU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/586964-322de14930c4452ba8ae7434db1e9eac.jpg']
          INFO: 19-Jan-24 18:15:12 	HTTP Request: HEAD https://www.allrecipes.com/thmb/jhwH3oEpLmIcJ4Adf4bRsvEJ0UU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/586964-322de14930c4452ba8ae7434db1e9eac.jpg "HTTP/1.1 200 OK"
          INFO: 19-Jan-24 18:15:12 	HTTP Request: GET https://www.allrecipes.com/thmb/jhwH3oEpLmIcJ4Adf4bRsvEJ0UU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/586964-322de14930c4452ba8ae7434db1e9eac.jpg "HTTP/1.1 200 OK"
          INFO: 19-Jan-24 18:15:12 	original.jpg minified
          INFO: 19-Jan-24 18:15:12 	Tiny image saved
          INFO: 19-Jan-24 18:17:45 	HTTP Request: GET https://www.crock-pot.com/on/demandware.store/Sites-crockpot-Site/default/Content-BlogLanding?fdid=recipes "HTTP/1.1 403 Forbidden"
          ERROR: 19-Jan-24 18:17:45 	Recipe Scraper was unable to extract a recipe.
          INFO: 19-Jan-24 18:17:45 	HTTP Request: GET https://www.crock-pot.com/on/demandware.store/Sites-crockpot-Site/default/Content-BlogLanding?fdid=recipes "HTTP/1.1 403 Forbidden"
          INFO: 19-Jan-24 18:18:06 	HTTP Request: GET https://www.crock-pot.com/on/demandware.store/Sites-crockpot-Site/default/Content-Show?cid=sweet-and-spicy-orange-chicken "HTTP/1.1 403 Forbidden"
          ERROR: 19-Jan-24 18:18:06 	Recipe Scraper was unable to extract a recipe.
          INFO: 19-Jan-24 18:18:06 	HTTP Request: GET https://www.crock-pot.com/on/demandware.store/Sites-crockpot-Site/default/Content-Show?cid=sweet-and-spicy-orange-chicken "HTTP/1.1 403 Forbidden"

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
> I have verified that this issue is not related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by 1) checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, 2)
verifying that there are errors in the log related to application level code, or
> 3) verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

As far as I can tell, this site isn't supported at all by the recipe scrapers library. In your logs I see:
> Recipe Scraper was unable to extract a recipe.

This website also doesn't appear on [the list of supported sites](https://github.com/hhursev/recipe-scrapers?tab=readme-ov-file#scrapers-available-for). Just to be absolutely sure, I tried sending a curl request to the URL you provided, and observed that the website doesn't expose any of the recipe data.

Unfortunately, since it isn't supported by recipe-scrapers (and can't be supported) there's nothing additional we can do
