### ISSUE TITLE
[BUG] - Possible to edit cookbook without being logged in

### ISSUE THREAD

**Issue by phellarv** [mealie-recipes/mealie#3098]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Go to https://<yourmealiesite>/cookbooks without being logged in.
There you can edit cookbooks, again without being logged in.
This is a severe security issue.

### Steps to Reproduce

1) Go to https://<yourmealiesite>/cookbooks without being logged in.
2) There you can edit cookbooks, again without being logged in.
![2024-02-02_14-10](https://github.com/mealie-recipes/mealie/assets/822762/78a95855-9ef6-4507-b85a-fe55b94d239e)

### Please provide relevant logs

```
INFO:     127.0.0.1:56788 - "GET /api/app/about HTTP/1.1" 200 OK
INFO:     172.16.40.1:10338 - "GET /api/explore/cookbooks/home?page=1&perPage=-1&orderBy=position&orderDirection=asc HTTP/1.1" 200 OK
INFO:     172.16.40.1:10338 - "GET /sw.js HTTP/1.1" 304 Not Modified
```

### Mealie Version

Version - nightly
Build - 9bf2e3fabd4bb9dce72f472ae13e064b5e9f6b78 

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Hey, thanks for raising this issue. 

I know that we currently have a few pages that are unsecured and can be accessed when a non logged-in user does access them directly. But the cookbook page is as far as i know not one of them and should reroute you to your last location. 

I wasn't able to reproduce this on my instance nor on the demo instance. 
E.G. by going to https://demo.mealie.io/g/home/cookbooks i get an 404 error (because router back is not accessible when directly navigating to that page)

Could you try to reproduce the problem on the demo page, or give more information about how to reproduce it.

**Comment by phellarv** [comment]
![2024-02-02_14-36](https://github.com/mealie-recipes/mealie/assets/822762/da195d13-dd35-4455-a961-396db9196fa1)
Yes it's possible on the demo site.

The thing I did:
I have a wordpress blogg. There I have a menu item that is a Custom Link. 
You can go to https://foodie.duckboot.net and click the menu item which is named mat to see the bug in action.

**Comment by Kuchenpirat** [comment]
Ok, this is verry weird. 
I don't know exactly why the router back would not be working when comming from a different source. Good news is that i was already working on adressing this for pretty much all pages, so this will be fixed within the next days. 

Thanks for helping me reproduce this!

**Comment by michael-genson** [comment]
Strange that you can directly link there, but only in certain instances.

This isn't a security issue because you can't actually edit the cookbook, it just looks like you can
