### ISSUE TITLE
Deleting ingredient from food data blanks the entry in recipies

### ISSUE THREAD

**Issue by TheHYPO35** [mealie-recipes/mealie#3225]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

I submitted this as a feature request and was asked to submit it as a bug.

Deleting a food data entry results in the name of that food item being blanked from an ingredient entry in a recipe.

It would be nice to either have a validation with a warning pop up if you are deleting an entry that is used in any existing recipes, and/or have any entries that contain the food item add the name of the food item back to the "notes" field. Otherwise, deleting a food item can unintentionally delete important information from a recipe. There may be other even better handling suggestions, but those were the two I came up with.

### Steps to Reproduce

Delete an ingredient from the food entry database [in the 'manage data' section of user account home page] that is already in use in a recipe with ingredient-amounts turned on.

### Please provide relevant logs

The only log is for the deletion:

>INFO: 26-Feb-24 15:05:34 	Deleting item with id 1d1b9908-4fad-44df-9bdb-f93f5c821f3e

### Mealie Version

v1.2.0  - [42a33cd993b4638f181d4083a7c5d21bf110e4e4]

### Deployment

Docker (Linux)

**Comment by RealFoxie** [comment]
I think the original string (used for parsing) also gets saved. So it could maybe display this again (instead of the 'old food name') as long as no food is chosen.

**Comment by TheHYPO35** [comment]
You're right, because you can click the 3-dot menu and see the original text. The only issue is that that it remains in "food quantity mode", so you will still have the quantum, measurement, and note - only the food name is deleted. it will just be 500ml [blank] crushed - and you can't convert one ingredient to "plain text". So it would have to clear the other fields and put the original text in the "notes" section.
I don't know if that's the desirable resolution, since the user won't necessarily be aware the one ingredient is not properly parsed for the purposes of the "scaling" function. I think it would simply make more sense perhaps to even prohibit deleting an ingredient that is currently in use? Hell, even editing the name of an ingredient once it's already in use can cause problems people might not realize. They might go in there and replace "diced onion" with just "onion" and add "diced" to the note, not realizing that "diced onion" was also used in another recipe that is now missing the word "diced". It's a bit dangerous to edit ingredients this way.    On Monday, February 26, 2024 at 03:32:17 p.m. EST, RealFoxie ***@***.***> wrote:  
 
 


I think the original string (used for parsing) also gets saved. So it could maybe display this again (instead of the 'old food name') as long as no food is chosen.

**Comment by gehrleib** [comment]
I'd like to suggest adding a column that counts the number of recipes tied to a tag, category, or tool.

**Comment by codefaux** [comment]
-- EDIT: Removed; Irrelevant and off-topic. My apologies. --

**Comment by codefaux** [comment]
Success.

I use Mealie solely in a docker container. If you don't, YMMV a tiny bit, but the process same-y.

Step zero: **_BACKUP EVERYTHING._** (Mealie has a backup function, I also stopped the containers and made a zip of the filesystem to be double-sure. You could take a db snapshot as well. If you don't know how, ask first, this is the last time before it's "too late.")

First:
Make ABSOLUTELY SURE that no recipe uses your ingredient-to-remove.  Go to `Search`, click `Foods`, and tick the box with your target Ingredient in the dropdown. No recipes should appear -- if they do, edit them to use the correct ingredient, and check again before proceeding.

**_If you remove this Ingredient while it is still being referenced, your Mealie instance might break in unexpected ways. You have been warned._**

Then:
Stop Mealie grafecully aka `docker stop mealie`, `systemctl stop mealie`, etc ..

Open your Mealie's DB in your browser/viewer of choice
- If you're using sqlite (aka "I don't have a database server/container supporting Mealie") I suggest sqlitebrowser (docker container `lscr.io/linuxserver/sqlitebrowser` is what I use.)
- If you're using postgres (aka "I DO have a database server/container supporting Mealie") I suggest Beekeeper or similar.

Find the Ingredient in table `ingredient_foods` and locate the row containing the Ingredient you wish to remove.
- `name` or `name_normalized` are the ingredient's name, and are good columns to sort by

OPTIONALLY: Copy the `uuid` value. Search the entire database for the `uuid` value. The ONLY entry should be this one. Do not proceed if there are multiple entries. I used the cli to dump the DB, and `grep` to search for the UUID. I couldn't see how to do a full-text search w/ Beekeeper. I'll go into more detail if someone needs it.

If you've verified the `uuid` for this Ingredient does not appear elsewhere, delete the entire row. Don't erase cells, your DB tool has a "delete row" function somewhere -- find it. (Beekeeper: Right click any cell in the row to delete, and click `Delete Row`)

Note: If your tool requires it, click Save/Apply/Commit/etc to ensure the action has been completed, rather than queued.

Close the file/connection in your Database tool, and restart Mealie -- _watch Mealie's logs, just in case._

It should all be fine. If not, stop Mealie and your database server/container, restore the backup, and try again.

If anyone needs help with the process, be detailed what you need and I'll try to fill in the gaps.

**Comment by TheHYPO35** [comment]
To be honest, I'm not sure what your solution is looking to 'solve'.

The original issue is that deleting an ingredient that is used in a recipe blanks the ingredient in that recipe. Your solution starts out with making sure manually that the ingredient is not used in any recipes, which means you are not solving the problem this thread is talking about.

As a separate note, you are basically just describing how to delete a row in the database. Does deleting the ingredient in the actual UI not achieve this same thing?

**Comment by codefaux** [comment]
EDIT: Yeah, I misread the original, -AND- I just found the builtin functionality to serve my need. Ignore me.

**Comment by codefaux** [comment]
To address/explain/agree with the original issue, so I'm not just wasting everyone's time:


When you create a new Ingredient, Mealie creates a UUID for it, tagging the entry with the name you've assigned, and a simplified version of that name, as well as a few other items.
![image](https://github.com/user-attachments/assets/fe5cfdd3-407c-4421-b430-0fb666d8f17f)

When a Recipe uses an Ingredient, the Recipe references the Ingredient by a unique identifier code aka UUID. When displayed on the screen, the UUID is converted back into the appropriate named item.

This is also why you can rename an Ingredient (to correct typos, for example) and it will be fixed in all recipes which use the same Ingredient.

If you remove the Ingredient from the database, its UUID/Name/etc are removed, but the Recipes aren't back-processed to remove the Ingredient references. That is to say, the Recipe isn't told that its Ingredient doesn't exist anymore. It's still asking for the Ingredient by UUID.

The "fix" for this would be for Mealie to prune Recipes for non-existent Ingredients and remove them, as a cleanup function when removing an Ingredient. I can agree that to the user this would seem like a "bug" more than a "self issue."

**Comment by TheHYPO35** [comment]
I appreciate you meant well, but yes - there is already functionality to delete an ingredient from within the UI. The problem (as noted in the original post) is that it does not warn you that you are deleting an ingredient that is still in use, or otherwise fix the recipe that now has a blank ingredient. And I agree it's not exactly a bug, but as you may note, I posted it as a feature request and was advised to make it a bug report.
