### ISSUE TITLE
[BUG] - Translation problem after feature #3271

### ISSUE THREAD

**Issue by fisch923** [mealie-recipes/mealie#3289]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [ ] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

After update to Mealie version 1.3.2 from 1.3.1 the button for adding ingredients is in english and not translated german:

![Screenshot 2024-03-11 204136](https://github.com/mealie-recipes/mealie/assets/140748672/121bb42c-4ebf-4124-87cd-9501188a18cf)

Is this issue already solved in nightly build? In https://demo.mealie.io/ the translation is correct
Is this Problem caused of the PR? https://github.com/mealie-recipes/mealie/pull/3271

### Steps to Reproduce

Update from 1.3.1 to 1.3.2 german translation

### Please provide relevant logs

n/a

### Mealie Version

1.3.2
Build: [b54cdf642505bcb63384bddcc21f15d751c2f85b](https://github.com/mealie-recipes/mealie/commit/b54cdf642505bcb63384bddcc21f15d751c2f85b)
DB: SQLite

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This is because it's not translated into German yet. That word was added in https://github.com/mealie-recipes/mealie/pull/3271, so that makes sense.

Our translations are done through Crowdin ([more info here](https://docs.mealie.io/contributors/translating/)), so once someone translates the word "Add" a PR will automatically be generated and it will get updated in the next release
