### ISSUE TITLE
[BUG] importing recipe from shared link duplicates last recipe added

### ISSUE THREAD

**Issue by sdetweil** [mealie-recipes/mealie#3296]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

trying to import vi url recipe from shared link.  
get successful import, but content is duplicate (1) of prior recipe import

### Steps to Reproduce

from recipe share
use linknto import, same or different group

### Please provide relevant logs

don't have

### Mealie Version

latest docker as or March 9, 2024

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This is expected behavior, as groups are completely isolated instances. More on that here: https://github.com/mealie-recipes/mealie/discussions/3301

Currently there is no way to share recipes between groups without duplicating them. If you import a recipe, it will be created as a new recipe (rather than shared). I wrote more detail on the discussion you raised (https://github.com/mealie-recipes/mealie/discussions/3301), but the behavior you're looking for doesn't exist currently.

**Comment by sdetweil** [comment]
no.. this is the scraper fails to import from the shared link... it is just another recipe... want to add it to my list (duplicate it) 

someone on the other side of the country wants to giv me a recipe... send me the link, I want to import from url..
it fails..  and creates a duplicate of the last recipe imported..  not this one

**Comment by michael-genson** [comment]
Ah I see, this is likely a duplicate of: https://github.com/mealie-recipes/mealie/issues/3068
