### ISSUE TITLE
Text color of food labels varies based on length of color code

### ISSUE THREAD

**Issue by jhinder** [mealie-recipes/mealie#3433]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

The text color (and by extension, text/background contrast) of a food label varies based on the length of the background color hex code.  
If the color has between 3 and 4 hex digits, the label always has a white text (even for very bright colors like `#EEE` or `#FFF`); if there are at least 5 hex digits, the text color varies based on contrast (expected behaviour).

![image](https://github.com/mealie-recipes/mealie/assets/823398/bfa9bb73-0fd9-492c-bcb6-eaad35bf1a1e)
![image](https://github.com/mealie-recipes/mealie/assets/823398/9d304078-faad-4b75-b1fd-65de993d01d0)

### Steps to Reproduce

1. Go to Data Management > Labels.
2. Add a new label and enter a name.
3. Set the hex code to `#EEE`.
4. Set the hex code to `#EEEEEE`.

### Please provide relevant logs

Not relevant, purely a UI issue.

### Mealie Version

Version
v1.4.0
Build
[f709d11952ca8552214e4b9e8c2a189bc11bfb2a](https://github.com/mealie-recipes/mealie/commit/f709d11952ca8552214e4b9e8c2a189bc11bfb2a)

### Deployment

Docker (Linux)

**Comment by Kuchenpirat** [comment]
Can reproduce the issue. 
This is because we expect a 6-digit rgb value [in the function](https://github.com/mealie-recipes/mealie/blob/faf716cb7e60b9e31451bdc1caec88e8a78f4db7/frontend/components/Domain/ShoppingList/MultiPurposeLabel.vue#L36)  that evaluates the Background Color and determins the appropiate text Color. 

The Chip color is set through Vuetify that can handle [multiple color formats](https://v2.vuetifyjs.com/en/api/v-chip/#props-color). 
There is also the issue that this does not take the opacity into account, which is supported even through the gui.
