### ISSUE TITLE
[BUG] - Changing the group of a user, removes all recipes from their account.

### ISSUE THREAD

**Issue by shomilsaini** [mealie-recipes/mealie#3839]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Changing the group of a user, removes all recipes from their account.
If the group is changed back the recipes reappear.

### Steps to Reproduce

Create a user
add the user to a group
create a recipe
change user's group to something else
Recipes gone.
Change the group to original
Recipes reappear.

### Please provide relevant logs

There is no error in logs.

### Mealie Version

ghcr.io/mealie-recipes/mealie:latest

Version
 v1.10.1

Build [d639d168fa7c39ffb802d46ba05e4ec4de33faf9](https://github.com/mealie-recipes/mealie/commit/d639d168fa7c39ffb802d46ba05e4ec4de33faf9)

### Deployment

Unraid

**Comment by shomilsaini** [comment]
Reproduced on the demo site.
Created user john/ password {johndoe1}
created recipe oatmeal
changed group to test(3)
Recipe is not shown because the system does not see john as owner of recipe. Recipe is visible on the admin login (default demo login) because it is shared/public etc.
change group back and everything is hunky-dory!

**Comment by michael-genson** [comment]
I agree that if a user changes groups, something has to happen to their recipes, but I'm not sure we want to move them to the new group, or if we want to just reassign them (similar to https://github.com/mealie-recipes/mealie/issues/3171).

Basically, when you switch the group of the user, their recipes still belong to the _old_ group, which is why the user can't see them anymore. The users of the old group can still see the recipes, their owner just moved. We should either:
1. Keep the recipes in the old group, but re-assign them to someone else
2. Re-assign the recipes to the new group, and thus the old group can't see the recipes anymore

Or a third option: disable switching the group of a user so this scenario can't even happen.

**Comment by shomilsaini** [comment]
They are user's recipes, they should move with user. Recipes should be tied to user not groups. Whatever user the group is in will have access. Also, the sharing system between users is overly convoluted.

Thanks
