### ISSUE TITLE
[BUG] - When printing a recipe the nutrition uom is not being shown

### ISSUE THREAD

**Issue by enrauk** [mealie-recipes/mealie#4125]
### First Check

- [X] This is not a feature request.
- [X] I added a very descriptive title to this issue (title field is above this).
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.
- [X] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

When printing a recipe the nutrition unit of measure is not being shown against the nutrition value

### Steps to Reproduce

1. Select a recipe with nutrition details
2. Select print preferences and turn on show nutrition if not selected
3. Print the recipe including the nutrition values

### Please provide relevant logs

No relevant logs

### Mealie Version

**Details**
Version: v1.11.0
Build: a41ad8c6ed968b43e5674ce77785dbdf76f77f57
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 15.0.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
OIDC Ready: No
OpenAI Ready: No
Email Configured: Yes

### Deployment

Docker (Linux)

### Additional Deployment Details

Not a deployment issue

**Comment by AitanBachrach** [comment]
Hello, I would like to take on this issue and have located the file i would need to change "frontend/components/Domain/Recipe/RecipePrintView.vue", and the value that would contain the UoM, recipe.recipeYield. However recipeYield is not required and a string and so could be many different formats. It does from the poking around I did seem to default to "# servings". Is there a way I should handle this? Additionally because the value is again from what I could figure out divorced from nutrition there is no guarantee that the nutrition values are per serving. How should I handle this?
