### ISSUE TITLE
AkiPetretzikis - Cannot scrape

### ISSUE THREAD

**Issue by dimpan** [mealie-recipes/mealie#4350]
### First Check

- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I have verified that this issue _is not_ related to the underlying library
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers) by **1)** checking
the [debugger](https://demo.mealie.io/g/home/r/create/debug) and data is returned, **2)**
verifying that there _are_ errors in the log related to application level code, or
**3)** verified that the site provides recipe data, or is otherwise supported by
[hhyrsev/recipe-scrapers](https://github.com/hhursev/recipe-scrapers)

- [X] This issue can be replicated on the demo site (https://demo.mealie.io/)

### Please provide 1-5 example URLs that are having errors

https://akispetretzikis.com/en/recipe/118/to-pastitsio-toy-akh

https://akispetretzikis.com/recipe/118/to-pastitsio-toy-akh

### Please provide your logs for the Mealie container `docker logs <container-id> > mealie.logs`

i do not know how to get logs with portainer for linux, however it doesnt work on the example/demo site either.

### Deployment

Other

**Comment by Kuchenpirat** [comment]
It appears that AkiPetretzikis is preventing our scraping attempt. This is due to ongoing issues between AI companies and content providers, and unfortunately, Mealie has been caught in the crossfire.

You can work around this by using the nightly image. Then copy the raw HTML and import the recipe by selecting "Import from HTML or JSON" on the recipe creation page.
