### ISSUE TITLE
Fuzzy search should include ingredients and other fields

### ISSUE THREAD

**Issue by DYLaKo** [mealie-recipes/mealie#713]
**Describe the bug**
When searching for an item (for example, an ingredient) in Mealie, the recipies with the specific ingredient do not come up.

**Steps To Reproduce**
1. Add multiple recipies with for example "karnemelk" or "ketchup".
2. Use the search function to search for "karnemelk" or "ketchup". The recipies do not appear in the results.

**Expected behavior**
When searching for "karnemelk", I would like to see all recipies with "karnemelk". Same for other ingredients.

**Actual Behavior**
When searching for "karnemelk", nothing appears.

**Screenshots**

**Device Information (please complete the following information):**
 - OS: Windows 10
 - Deployment: Running Mealie 0.5.2 in Docker on Photon OS 4 using the Docker Compose version, sqlite db.
 - Browser: Microsoft Edge
 - Version:  94.0.992.31

**Additional context**
Tried to search for keywords in the recipe itself, this doesn't work either.

**Comment by hay-kot** [comment]
This is because the current fuzzy search doesn't search through ingredients. At the current version all search is done on the client side and as such we're searching through summary objects that don't contain ingredients. To implement something like you're asking we'd need to find a way to do searches on the server side. At the moment I haven't found any viable alternatives that are fast enough to get results that doesn't require an additional application/container. 

I'm open to suggestions on how we can improve the search functionality, I agree that it isn't optimal.

**Comment by DYLaKo** [comment]
> This is because the current fuzzy search doesn't search through ingredients. At the current version all search is done on the client side and as such we're searching through summary objects that don't contain ingredients. To implement something like you're asking we'd need to find a way to do searches on the server side. At the moment I haven't found any viable alternatives that are fast enough to get results that doesn't require an additional application/container.

That explains a lot. I am afraid it makes Mealie not the solution for me then. I want to use it mainly to build an index of the recipies in my cookbooks with the oppertunity to search for recipies by entering a specific ingredient I want to use. 

Which fields are searched through the currently implemented search feature? 

> I'm open to suggestions on how we can improve the search functionality, I agree that it isn't optimal.

I wish I could help out with this, but I am just a simple user, no programmer.  :-(

**Comment by hay-kot** [comment]
FWIW, if v1 I'll be adding some-sort of feature where you can filter based off ingredient.
