### ISSUE TITLE
Android Firefox PWA icon looks unpleasant

### ISSUE THREAD

**Issue by reeseovine** [mealie-recipes/mealie#758]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

The icon for the progressive web app when installed from Firefox for Android has an oversized orange icon on a slightly different orange background, whereas when installed from Chromium it has a normal sized icon on a white background.

![Screenshot_20211027-000544_Trebuchet](https://user-images.githubusercontent.com/1340784/139003849-4125c6ce-7d7b-49d2-b9de-31a799d001f9.png)

The one on the left was installed by Fennec F-droid (alternative build of Firefox). I have tested with the official Firefox app which has the same issue. The one on the right is from Bromite (Chromium). I have not tested with Google Chrome but I am assuming it looks correct there.

### Deployment

Docker (Linux)

### Mealie Version

v0.5.2

**Comment by hay-kot** [comment]
Is this a problem with Mealie, or a problem with Firefox? I think it's the browser that determines what that icon looks like, we provide an icon, but it looks like they use the primary color to set the background. I'm not sure that's something we can deal with there.

**Comment by reeseovine** [comment]
It could be, I'm not totally familiar with PWA or app icons so I'm not sure who's to blame here. I'll look into it, and if it's an easy fix I can open a PR.

**Comment by reeseovine** [comment]
I can't seem to get Mealie to run on my dev machine. My guess is that you just need to make a couple icons named `android-launchericon-W-H.png` with the logo scaled down to fit inside a circle and with a white background, then add them to manifest.json. Something like this:
![android-launchericon-192-192](https://user-images.githubusercontent.com/1340784/139482621-76916020-9f53-4aeb-ab34-f95cb797155d.png)

SVG: [android-launchericon.zip](https://github.com/hay-kot/mealie/files/7444107/android-launchericon.zip)

manifest.json:
```json
{
  "icons": [
    {
      "src": "./web-icons/android/android-launchericon-192-192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "./web-icons/android/android-launchericon-512-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
```

**Comment by pR0Ps** [comment]
The icons [already exist](https://github.com/hay-kot/mealie/tree/dev/frontend/public/img/icons) and are properly specified by [the manifest](https://github.com/hay-kot/mealie/blob/dev/frontend/public/manifest.json). The issue is that the icons have a transparent background and Firefox seems to be using the [`theme_color`](https://developer.mozilla.org/en-US/docs/Web/Manifest/theme_color) attribute from the manifest as the background color.

Since the `theme_color` controls how the app looks when it's launched, changing it doesn't seem like right solution. Just adding a white background to all the images should fix the issue without changing anything else.

**Comment by cadamswaite** [comment]
> adding a white background to all the images should fix the issue without changing anything else

I'd like to avoid this solution if possible, since the transparency can be handled well by other programs (e.g. adding a link to home screen in using Chrome on Android allows background to be seen through the transparency. Similarly ios fills in the background with a different colour - according to the docs. I don't have one so can't test.)

My main concern is that when PWAs allow for dark mode, then having a solid white square in a black splash screen would look silly.

I've spent some time playing around with it today and think I've found something that works for both FF and Chrome.
I'll do some more testing and try to get a PR in tomorrow

**Comment by cadamswaite** [comment]
In case people are interested, I spent some more time looking into this.
It's a [known bug in Firefox](https://github.com/mozilla-mobile/fenix/issues/9916) - not sure if anyone has re-raised the issue since it was last auto-closed.

This is where I got to yesterday - better, but not great:
PWA installed in Chrome is on the left, link to the website (Chrome based) in the middle and Firefox's attempt on the right.
![image](https://user-images.githubusercontent.com/8062095/139600448-3d2f7978-acf0-4dc9-bc2a-9b41311f96a1.png)
When I tried this on an older Android (with latest FF), I got the same orange logo as reported - so think white backgrounds are only real solution until PWAs are better handled/defined.

I have no idea how FF/Android is trying to handle this transparency - looks like a fun bug. 
I assumed it was just the mean colour, but seems to be somehow weighted:
![image](https://user-images.githubusercontent.com/8062095/139600532-7d4ad743-ff98-4733-af82-be46e5b9ca33.png)

Anyway, the PR linked above worked for me - hopefully it works for IOS etc too
![image](https://user-images.githubusercontent.com/8062095/139600651-17c42299-eded-4dba-aec5-8bc4553d23f3.png)
