### ISSUE TITLE
[v1.0.0b] - Shopping List initial feedback

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#942]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

Great work hay-kot.  Shopping lists are really coming alot.   I documented anything I noticed as I tested.  Some of it may be preference feedback, feel free to ignore.  Trying to be as detailed as I can.

1) Shopping list action buttons.  First button (2 pages) doesn't have a mouseover tooltip.
2) Have an empty shopping list.  Make 2 shopping items, using the food textbox (instead of note textbox).  Drag the 12-dot mover button to reorder.  The one food item will eat other food item, and increment it's quantity number.
3) What's the difference between entering a food item and a note item?  Should the label get autopopulated for the food item?  I found food item label didn't get populated.   I did not understand the difference between a food item and a note item.
4) Once you hit create item, and you get the create box.  Should the create item action buttons be in the box?  As a first time user it was a little confusing that I have two rows of buttons.  One was for the item, and one was for the list.
5) When you are creating item for shopping list, what is the difference between Delete and Cancel?
6) Each time you want to create a shopping list item, you need 3 mouseclicks (Create button, click on note, hit save).  For usability, perhaps autofocus to note/food textbox (depending on preference)
7) Would be nice to have some kind of batch mode to enter lots of items at once.
8) When you toggle label sort,   manual sorting becomes impossible.  Perhaps hide the sort dragger.
9) When label sort is toggled,  do we need the label buttons anymore?  We already have the label titles.
10) I had a 5 item (notes) shopping list,  i checked one item,  then hit Uncheck All Items.   It deleted my checked item, and incremented units of another item.   Was hard to replicate, only saw it happen once.
11) If you hit manage labels.  Once complete, you can't go back to your working shopping list.  You have to click through ShoppingLists, and pick your Shopping list again.
12) Could we add a priority/sort to the shopping list labels so it will sort according to our grocery store?
13) If you hit edit shopping list item,  create button still exists.  If you hit create button while edits, it has 2 create/edit boxes open at once.
14) Should the label combo box be sorted alphabetically instead of the creation order?
15) When adding food and note labels, should the note be italicized or something to differentiate from food item text?
16) Toggle food choice should be remembered.   If you toggle to add food items, presumably you want to keep doing food items.
17) If you toggle food in the creation box, it should probably autofocus to Food textbox.

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
I've divided your comments into two sections, Bug and User Experience, is this list accurate? 

## Bugs
1. Have an empty shopping list. Make 2 shopping items, using the food textbox (instead of note textbox). Drag the 12-dot mover button to reorder. The one food item will eat other food item, and increment it's quantity number.
2. I had a 5 item (notes) shopping list, i checked one item, then hit Uncheck All Items. It deleted my checked item, and incremented units of another item. Was hard to replicate, only saw it happen once.

I was able to replicate both of these issues. There appears to be some bugs with the consolidation algorithm. I'll have to identify some additional test-cases to cover all possible merge scenarios. There's definitely some odd and unexpected behavior going on. 

## User Experience 
1. Shopping list action buttons. First button (2 pages) doesn't have a mouseover tooltip.
2. What's the difference between entering a food item and a note item? Should the label get autopopulated for the food item? I found food item label didn't get populated. I did not understand the difference between a food item and a note item.

    _Currently they're only auto-populated when they are taken from a recipe. It does make sense for the label to work for manual entries as well. As for the difference, It's mostly just a preference? If a food/unit is present there's a formula to determine the text output, otherwise it's just quantity + note. Adding foods and units is helpful mostly for recipe to list mappings_ 

3. Once you hit create item, and you get the create box. Should the create item action buttons be in the box? As a first time user it was a little confusing that I have two rows of buttons. One was for the item, and one was for the list.

    _I agree it's not ideal. I think the buttons look funny inside the box. My wife suggested making the main action bar floating when you scroll past it, which may be an option. I'm still mulling over how to display the main bar._  🤷‍♂️

4. When you are creating item for shopping list, what is the difference between Delete and Cancel?

   _Nothing? I should remove delete when creating a new item_

5. Each time you want to create a shopping list item, you need 3 mouseclicks (Create button, click on note, hit save). For usability, perhaps autofocus to note/food textbox (depending on preference)
6. Would be nice to have some kind of batch mode to enter lots of items at once.

    _I'm open to this. Hopefully someone else can jump on it. I don't expect to use the manually entry much as the key feature is the mapping from a recipe to a shopping list_ 

7. When you toggle label sort, manual sorting becomes impossible. Perhaps hide the sort dragger.
8. When label sort is toggled, do we need the label buttons anymore? We already have the label titles.
9. If you hit manage labels. Once complete, you can't go back to your working shopping list. You have to click through ShoppingLists, and pick your Shopping list again.
10. Could we add a priority/sort to the shopping list labels so it will sort according to our grocery store?

    _I'm open to it. How would you expect this to work? Assigning a number value to the label be sorted by?_ 

11. If you hit edit shopping list item, create button still exists. If you hit create button while edits, it has 2 create/edit boxes open at once.

    _The component needs a more defined edit/create mode so I can control these. I agree that it's not immediately clear._

12. Should the label combo box be sorted alphabetically instead of the creation order?

    _Yes_ 

13. When adding food and note labels, should the note be italicized or something to differentiate from food item text?

    _Ehhh. I could go either way on this, I'd be more inclined to add a "-" or something after the food. Mostly because 
    italicizing a computed text value would be more difficult._ 

14. Toggle food choice should be remembered. If you toggle to add food items, presumably you want to keep doing food items.
    
    _Yes_    

15. If you toggle food in the creation box, it should probably autofocus to Food textbox.

    _I agree, I'll see if I can make this work._

---

I REALLY appreciate these feedback posts. In the feature, would you be able to divide the feedback into Bugs/User-Experience categories? Helps me prioritize and make sure I understand the feedback 👍

**Comment by coffee-mage** [comment]
Thanks for the feedback, I will try to group to these 2 categories in the future.

**Comments:**
Label Priority for sorting -- I think a number works,  or a dragger in the label manager that keeps a number hidden based on position.  Whatever is easiest. 

Manual Entry -- I'm not sure if i'm an outlier here, but I think manual might get used more than you expect.  Probably people build the shopping list based on several exciting dinners meals, and a bunch of essentials they always want to have.  As an example, i'm probably not going to add a bunch of these 'recipes' to the shopping list.  But i always want to have eggs, bacon, bread, and cereal in the house for breakfast.     I firmly believe, your app, your vision.  Just providing some context of my thoughts.

"Currently they're only auto-populated when they are taken from a recipe. It doesn't make sense for the label to work for manual entries as well. As for the difference, It's mostly just a preference? If a food/unit is present there's a formula to determine the text output, otherwise it's just quantity + note. Adding foods and units is helpful mostly for recipe to list mappings"
I just want to make sure i'm clear here.  You are saying the food items get populated automatically from recipes, but labels don't get populated automatically?

Thanks for all your fantastic work!

**Comment by hay-kot** [comment]
> It doesn't make sense 

I meant does make sense. Whoops. Fixed that above. When an entry is first added and has a food it **SHOULD** get the foods label automatically assigned. 

> Manual Entry -- I'm not sure if i'm an outlier here, but I think manual might get used more than you expect. 

You're probably right. I'll definitely add a Task item for this, but it's not a release blocker so I'll probably move forward without fixing this for a while.

**Comment by brainstorm** [comment]
Given multiple recipes, would it be possible to collapse similar shopping list items (fuzzy pattern matching)? I see quite a few duplicates, which makes the output a bit impractical when I'm being in a rush at the supermarket :-S

Haven't tried [RecipeSage](https://recipesage.com/) yet, but they claim:

> Shopping lists: Automatically categorized and intelligently grouped - add your recipes directly to a shopping list and similar items will be combined

EDIT: Nevermind, seems like this feature is being [tackled/tested actively in beta](https://github.com/hay-kot/mealie/issues/1190), I might give it a try later on.

**Comment by tionis** [comment]
Regarding shopping list experience: why are labels and categories different?
If I add the ingredients of a recipe to the shopping list I want it to be sorted by the categories attached to the food items, not have to put manual labels on each of them.

**Comment by hay-kot** [comment]
> why are labels and categories different?

Categories are for Recipes and Labels are for individual foods. Foods don't have categories so I'm not sure what you mean.

There was a bug where when you added a food to the shopping list the label didn't carry over, but that has been fixed.

**Comment by tionis** [comment]
I'm running on docker so maybe I don't have the fix yet. I just switched to english in the interface and indeed they are both called label.  
The problem I hat was that the food had the visual label marker but wasn't sorted under unlabeled.
