### ISSUE TITLE
[v1.0.0b] - Email 'send test' errors but gives no error code or explanation

### ISSUE THREAD

**Issue by zierbeek** [mealie-recipes/mealie#996]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When sending a test e-mail, It errors out but that is not the bug. The fact that the status stays empty is what is the issue. The logs of mealie api also show no log describing this specific error. When the test e-mail was successful, It also shows the line 'errors:' and is empty. 

`172.18.0.10:55216 - "GET /api/users/self HTTP/1.1" 200
172.18.0.10:55218 - "GET /api/admin/about HTTP/1.1" 200
172.18.0.10:55222 - "GET /api/admin/about/check HTTP/1.1" 200
127.0.0.1:47214 - "GET /docs HTTP/1.1" 200
INFO: 23-Feb-22 10:07:28 	send email result: <emails.backend.SMTPResponse status_code=None status_text=None>
172.18.0.10:55234 - "POST /api/admin/email HTTP/1.1" 200
127.0.0.1:47236 - "GET /docs HTTP/1.1" 200
`

<img width="327" alt="Schermafbeelding 2022-02-23 om 10 08 14" src="https://user-images.githubusercontent.com/58994651/155289758-40e83c0f-f52b-4bba-87b7-a2877b65839b.png">

### Deployment

Docker (Linux)

**Comment by hay-kot** [comment]
Working on a fix for this that removes the Error: since we're not returning anything to the frontend to tell the user what the error is. I did update some code to log the error but in most cases it wasn't very helpful, those come directly from the emails package in python so not much I can do there 🤷 

<img width="899" alt="CleanShot 2022-02-23 at 14 00 25@2x" src="https://user-images.githubusercontent.com/64056131/155424010-67aefa87-e6f1-4551-b021-7c4d92f591de.png">
