### ISSUE TITLE
[v1.0.0b] - On Allrecipes page, any recipe without image displays 404 in console.

### ISSUE THREAD

**Issue by coffee-mage** [mealie-recipes/mealie#998]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

In allrecipes page, any recipe without an image (shows knife and fork) will spam 404 message to console.log
![image_404](https://user-images.githubusercontent.com/14890934/155295300-d2329628-a329-4873-aff9-36dd6a6b0365.JPG)

### Deployment

Other

### Deployment Details

beta.mealie.io

**Comment by hay-kot** [comment]
I'm not sure there's a good way around this at the moment. We'd have to have some kind of flag on the recipe to check if an image exists. 

This is a pretty low priority though since it doesn't effect the UX (at-least that I've noticed) and it shouldn't really harm performance too much considering all those requests are handled by the proxy server and not the API.
